import { Category, Product, BackupData } from "./storage";

const CATEGORIES: Category[] = [
  { id: "cat_ferramentas", name: "Ferramentas Manuais", color: "#3B82F6" },
  { id: "cat_eletricas", name: "Ferramentas Elétricas", color: "#EF4444" },
  { id: "cat_soquetes", name: "Soquetes e Encaixes", color: "#8B5CF6" },
  { id: "cat_brocas", name: "Brocas e Serras", color: "#F59E0B" },
  { id: "cat_epi", name: "EPI", color: "#10B981" },
  { id: "cat_construcao", name: "Construção", color: "#F97316" },
  { id: "cat_medicao", name: "Medição", color: "#06B6D4" },
  { id: "cat_insumos", name: "Insumos", color: "#64748B" },
];

function makeProduct(
  name: string,
  categoryId: string,
  quantity: number,
  unit: string,
  index: number
): Product {
  const now = new Date().toISOString();
  return {
    id: `seed_prod_${index}`,
    name,
    categoryId,
    quantity,
    minStock: quantity <= 2 ? 1 : Math.max(1, Math.floor(quantity * 0.2)),
    price: 0,
    unit,
    createdAt: now,
    updatedAt: now,
  };
}

const c = {
  fm: "cat_ferramentas",
  fe: "cat_eletricas",
  sq: "cat_soquetes",
  bs: "cat_brocas",
  ep: "cat_epi",
  co: "cat_construcao",
  me: "cat_medicao",
  ins: "cat_insumos",
};

const PRODUCTS_RAW: [string, string, number, string][] = [
  ["Adaptador Impacto 1/2 para 3/4", c.sq, 2, "un"],
  ["Alicate Corte", c.fm, 7, "un"],
  ["Alicate Crimpagem", c.fm, 1, "un"],
  ["Alicate de Ponta", c.fm, 2, "un"],
  ["Alicate MC4", c.fm, 8, "un"],
  ["Alicate Rebitador", c.fm, 3, "un"],
  ["Alicate Universal", c.fm, 4, "un"],
  ["Arco e Serra", c.fm, 6, "un"],
  ["Balança digital portátil", c.me, 1, "un"],
  ["Bateria Parafusadeira", c.fe, 8, "un"],
  ["Bomba D'água Submersível", c.fe, 1, "un"],
  ["Broca Aço rápido - madeira", c.bs, 6, "un"],
  ["Broca Concreto n°8", c.bs, 6, "un"],
  ["Broca Concreto n°12", c.bs, 2, "un"],
  ["Broca Concreto n°6", c.bs, 6, "un"],
  ["Brocha", c.co, 7, "un"],
  ["Carregador Bateria Parafusadeira", c.fe, 5, "un"],
  ["Carrinho de mão", c.co, 4, "un"],
  ["Cavadeira", c.co, 2, "un"],
  ["Chave Catraca", c.fm, 3, "un"],
  ["Chave combinada 8", c.fm, 5, "un"],
  ["Chave combinada n°10", c.fm, 6, "un"],
  ["Chave combinada 13", c.fm, 11, "un"],
  ["Chave combinada 16", c.fm, 4, "un"],
  ["Chave combinada 17", c.fm, 3, "un"],
  ["Chave combinada 18", c.fm, 11, "un"],
  ["Chave combinada 19", c.fm, 2, "un"],
  ["Chave combinada 22", c.fm, 4, "un"],
  ["Chave combinada 24", c.fm, 12, "un"],
  ["Chave combinada 27", c.fm, 2, "un"],
  ["Chave combinada 28", c.fm, 3, "un"],
  ["Chave combinada 30", c.fm, 5, "un"],
  ["Chave de Fenda", c.fm, 1, "un"],
  ["Chave Impacto Dewalt 1/2", c.fe, 3, "un"],
  ["Chave Impacto Dewalt 3/4", c.fe, 1, "un"],
  ["Chave Impacto Makita 1/2", c.fe, 2, "un"],
  ["Chave Inglesa", c.fm, 2, "un"],
  ["Chave Philips", c.fm, 1, "un"],
  ["Colher Pedreiro", c.co, 4, "un"],
  ["Conjunto Bico Parafusadeira", c.fe, 1, "un"],
  ["Conjunto BITS 64mm DUPLO", c.fe, 1, "un"],
  ["Conjunto Serra Copo", c.bs, 2, "un"],
  ["Cortador de fio", c.fm, 1, "un"],
  ["Desempenadeira", c.co, 11, "un"],
  ["Diesel Janeiro 2026", c.ins, 100, "Litros"],
  ["EPI - Calça M", c.ep, 14, "un"],
  ["EPI - Camisa M", c.ep, 18, "un"],
  ["EPI - Óculos Transparente", c.ep, 172, "un"],
  ["Escova de aço", c.fm, 3, "un"],
  ["Espátula", c.fm, 5, "un"],
  ["Esquadro", c.me, 17, "un"],
  ["Formão", c.fm, 1, "un"],
  ["Furadeira - Parafusadeira", c.fe, 5, "un"],
  ["Inchada", c.co, 3, "un"],
  ["Lavanca", c.co, 4, "un"],
  ["Lixadeira", c.fe, 2, "un"],
  ["Mangueira Nível 5 metros", c.me, 1, "un"],
  ["Maquita", c.fe, 1, "un"],
  ["Marreta", c.fm, 6, "un"],
  ["Marreta Borracha", c.fm, 6, "un"],
  ["Marreta Grande", c.fm, 9, "un"],
  ["Marretinha", c.fm, 3, "un"],
  ["Martelete pequeno", c.fe, 2, "un"],
  ["Martelo", c.fm, 4, "un"],
  ["Matriz Prensa Incompleta", c.fe, 0, "un"],
  ["Misturador tinta", c.fe, 2, "un"],
  ["Multímetro Pequeno", c.me, 1, "un"],
  ["Nível de mão", c.me, 14, "un"],
  ["Nível Magnético 30cm", c.me, 4, "un"],
  ["Nível Magnético Dewalt 15cm", c.me, 1, "un"],
  ["Picareta", c.co, 2, "un"],
  ["Plumo", c.me, 23, "un"],
  ["Ponteiro", c.fm, 6, "un"],
  ["Prensa Hidráulica", c.fe, 2, "un"],
  ["Pá", c.co, 3, "un"],
  ["Rebitadeira Eletrônica", c.fe, 1, "un"],
  ["Serra Circular", c.fe, 2, "un"],
  ["Serra Copo 3''", c.bs, 1, "un"],
  ["Serra Copo 4''", c.bs, 1, "un"],
  ["Serrote", c.fm, 3, "un"],
  ["Soquete 8mm Parafusadeira", c.sq, 2, "un"],
  ["Soquete 10mm Curto", c.sq, 2, "un"],
  ["Soquete 10mm Longo", c.sq, 2, "un"],
  ["Soquete 10mm Parafusadeira", c.sq, 2, "un"],
  ["Soquete 11mm Longo", c.sq, 1, "un"],
  ["Soquete 13mm Longo", c.sq, 3, "un"],
  ["Soquete 14mm Longo", c.sq, 1, "un"],
  ["Soquete 15mm Curto", c.sq, 3, "un"],
  ["Soquete 15mm Longo", c.sq, 3, "un"],
  ["Soquete 16mm Longo", c.sq, 4, "un"],
  ["Soquete 17mm Curto", c.sq, 2, "un"],
  ["Soquete 18mm Curto", c.sq, 3, "un"],
  ["Soquete 18mm Longo", c.sq, 10, "un"],
  ["Soquete 21mm Curto", c.sq, 1, "un"],
  ["Soquete 22mm Curto 3/4", c.sq, 2, "un"],
  ["Soquete 22mm Longo 3/4", c.sq, 2, "un"],
  ["Soquete 24mm Curto 3/4", c.sq, 4, "un"],
  ["Soquete 24mm Longo 1/2", c.sq, 5, "un"],
  ["Soquete 27mm Curto", c.sq, 1, "un"],
  ["Soquete 28mm Longo", c.sq, 4, "un"],
  ["Soquete 30mm Curto", c.sq, 11, "un"],
  ["Soquete 30mm Curto 3/4", c.sq, 1, "un"],
  ["Soquete 30mm Longo", c.sq, 1, "un"],
  ["Talhadeira", c.fm, 5, "un"],
  ["Torquês", c.fm, 7, "un"],
  ["Torquímetro", c.fm, 4, "un"],
];

const PRODUCTS: Product[] = PRODUCTS_RAW.map(([name, catId, qty, unit], i) =>
  makeProduct(name, catId, qty, unit, i + 1)
);

export function getSeedData(): BackupData {
  return {
    version: 1,
    exportedAt: new Date().toISOString(),
    categories: CATEGORIES,
    products: PRODUCTS,
    movements: [],
  };
}
